### ISSUE TITLE
README.md doesn't acknowledge ski, the original emulator from HP

### ISSUE THREAD

**Issue by tommythorn** [iximeow/yaxpeax-ia64#5]
You seem to only account for binutils, but I would expect http://ski.sourceforge.net/ to be more cannon as it cames from the parents of IA-64.

**Comment by iximeow** [comment]
oh! that would be because i didn't know about ski. admittedly, i didn't think to look into itanium emulation either, just for disassemblers. of course, ski would have to include disassembly as part of emulation so that's certainly relevant for the README. thank you for letting me know!

**Comment by tommythorn** [comment]
NP, I'm sure your Rust creation is far more elegant, but Ski might be a handy reference
